name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: ''

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}